version: '3.6'

networks:
  network1:
    name: portainer-agent-network
    external: true
  
services:
  agent:
      image: portainer/agent:2.19.4
      ports:
        - "9001:9001"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /mydata/docker/lib/volumes:/var/lib/docker/volumes
      networks:
        - network1
      
      deploy:
        mode: global
        placement:
          constraints: [node.platform.os == linux]

  portainer:
    image: 6053537/portainer-ce
    environment:
      - DMIN_USERNAME:"admin"
      - ADMIN_PASS:"1234567891011"
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /mydata/portainer/data:/data
      # - /mydata/portainer/public:/public
    networks:
      - network1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
