version: "3.6"

networks:
  network1:
    name: gitlab-network
    external: true

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    ports:
      - "9822:22"
      - "9980:80"
      - "443:443"
    networks:
      - network1
    volumes:
      - /mydata/gitlab/data:/var/opt/gitlab
      - /mydata/gitlab/logs:/var/log/gitlab
      - /mydata/gitlab/config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    privileged: true
    secrets:
      - gitlab_root_password
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    deploy:
      mode: replicated
      replicas: 1
configs:
  gitlab:
    file: ./gitlab.rb
secrets:
  gitlab_root_password:
    file: ./root_password.txt
