
version: '3.7'

networks:
  network1:
    name: jenkins-network
    external: true

services:
  jenkins:
    image: jenkinsci/blueocean
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /mydata/jenkins/home:/var/jenkins_home
      - /mydata/jenkins/maven/apache-maven-3.5.4:/usr/local/maven
      - /mydata/jenkins/certs:/certs/client
    networks:
      - network1
    ports:
        - "8080:8080" 
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]